//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5420
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerTrans.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerTrans.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _111 {
            get {
                object obj = ResourceManager.GetObject("111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _123 {
            get {
                object obj = ResourceManager.GetObject("123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _1351127915_button_cross_red_副本 {
            get {
                object obj = ResourceManager.GetObject("1351127915_button-cross_red_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _1351127915_button_cross_red_副本1 {
            get {
                object obj = ResourceManager.GetObject("1351127915_button-cross_red_副本1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _1351127998_accepted_48_副本 {
            get {
                object obj = ResourceManager.GetObject("1351127998_accepted_48_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _18 {
            get {
                object obj = ResourceManager.GetObject("18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _2221 {
            get {
                object obj = ResourceManager.GetObject("2221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _26 {
            get {
                object obj = ResourceManager.GetObject("26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _27 {
            get {
                object obj = ResourceManager.GetObject("27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _35 {
            get {
                object obj = ResourceManager.GetObject("35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _36 {
            get {
                object obj = ResourceManager.GetObject("36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _37 {
            get {
                object obj = ResourceManager.GetObject("37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _38 {
            get {
                object obj = ResourceManager.GetObject("38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _400_F_40267889_tM4GFFqjItUMXFN8JMsSfZ1UPAR9q2ba {
            get {
                object obj = ResourceManager.GetObject("400_F_40267889_tM4GFFqjItUMXFN8JMsSfZ1UPAR9q2ba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _51 {
            get {
                object obj = ResourceManager.GetObject("51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _82701 {
            get {
                object obj = ResourceManager.GetObject("82701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _9045267_icono_brillante_de_salida {
            get {
                object obj = ResourceManager.GetObject("9045267-icono-brillante-de-salida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap add_2 {
            get {
                object obj = ResourceManager.GetObject("add_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string DSCPOSSETIP_INI {
            get {
                return ResourceManager.GetString("DSCPOSSETIP_INI", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap edit_1 {
            get {
                object obj = ResourceManager.GetObject("edit_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap edit_11 {
            get {
                object obj = ResourceManager.GetObject("edit_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Folder_Gear {
            get {
                object obj = ResourceManager.GetObject("Folder Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Greencheckboxwithcheckmark {
            get {
                object obj = ResourceManager.GetObject("Greencheckboxwithcheckmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2__1_ {
            get {
                object obj = ResourceManager.GetObject("img2 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2__2_ {
            get {
                object obj = ResourceManager.GetObject("img2 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2__3_ {
            get {
                object obj = ResourceManager.GetObject("img2 (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2__4_ {
            get {
                object obj = ResourceManager.GetObject("img2 (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_1 {
            get {
                object obj = ResourceManager.GetObject("L_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_11 {
            get {
                object obj = ResourceManager.GetObject("L_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_12 {
            get {
                object obj = ResourceManager.GetObject("L_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Login_02__1_ {
            get {
                object obj = ResourceManager.GetObject("Login-02 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Login_02__1_1 {
            get {
                object obj = ResourceManager.GetObject("Login-02 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap minus_1 {
            get {
                object obj = ResourceManager.GetObject("minus_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap minus_11 {
            get {
                object obj = ResourceManager.GetObject("minus_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [34]
        ///單店庫存查詢=DSCPOSQ01
        ///跨店庫存查詢=DSCPOSQ02
        ///轉撥單查詢=DSCPOSQ04
        ///公告查詢=DSCPOSQ05
        ///會員查詢=DSCPOSQ06
        ///當日查詢/當班查詢=DSCPOSQ07
        ///交易查詢=DSCPOSQ08
        ///選擇品號=DSCPOSQ09
        ///商品顏色尺寸選擇=DSCPOSQ10
        ///門市銷售日統計查詢=DSCPOSQ13
        ///付款方式統計查詢=DSCPOSQ13
        ///交易類別統計查詢=DSCPOSQ13
        ///品號銷售日統計查詢=DSCPOSQ13
        ///類別銷售日統計查詢=DSCPOSQ13
        ///時段統計查詢=DSCPOSQ13
        ///品號時段統計查詢=DSCPOSQ13
        ///類別時段統計查詢=DSCPOSQ13
        ///業務員業績查詢=DSCPOSQ13
        ///沖銷應收=DSCPOSQ14
        ///關單=DSCPOSQ15
        ///圖片查詢=DSCPOSQ18
        ///發票跳號查詢=DSCPOSQ19
        ///團務查詢=DSCPOSQ20
        ///預購查詢(新版)=DSCPOSQ21
        ///變更歷程查詢=DSCPOSQ22
        ///電子計算機發票=DSCPOSV01
        ///銷貨退回單=DSCPOSV02
        ///銷貨單=DSCPOSV03        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string PGName {
            get {
                return ResourceManager.GetString("PGName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap pkg {
            get {
                object obj = ResourceManager.GetObject("pkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pkg1 {
            get {
                object obj = ResourceManager.GetObject("pkg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap plus_1 {
            get {
                object obj = ResourceManager.GetObject("plus_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap plus_11 {
            get {
                object obj = ResourceManager.GetObject("plus_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap return_1 {
            get {
                object obj = ResourceManager.GetObject("return_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap return_11 {
            get {
                object obj = ResourceManager.GetObject("return_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [CustNo]
        ///Item00=社子花卉|0|61178401|C:\COSMOS_POS|21
        ///Item01=東凌|0|61121379|C:\COSMOS_POS|21
        ///Item02=金省錢|0|61461200|C:\COSMOS_POS|21
        ///Item03=清境農場|0|^^|C:\COSMOS_POS|21
        ///Item04=麗嬰|0|61191000|C:\COSMOS_POS|31
        ///Item05=滋味珍食品|0|61100401|C:\COSMOS_POS|31
        ///Item06=美的適|0|61171401|C:\COSMOS_POS|31
        ///Item07=上品|0|61491100|C:\COSMOS_POS|31
        ///Item08=白木屋|0|61113379|C:\COSMOS_POS|31
        ///Item09=歐立|0|02161202|C:\COSMOS_POS|31
        ///Item10=藍海|0|61125379|C:\COSMOS_POS|31
        ///Item11=玩媒體|0|61155379|C:\COSMOS_POS|31
        ///Item12=睡眠|0|61195379|C:\COSMO [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對外_POS34=DataSet.bin|DATASET.EXE|DSCPOSDEVICE.EXE|POSInstall.exe|POSMAIN.EXE|POSVCLGP_150.bpl|LDRESGP.dll|INPOUT32.DLL|IndySystem150.bpl|IndyProtocols150.bpl|IndyCore150.bpl|DSCPOSL01.dll|AlterDB.exe|CHECKCONNECTION.EXE|UPDATEFILE.EXE|WPOCMD.DLL|
        ///對外_GPPOS2.0=AlterDB.exe|CHECKCONNECTION.EXE|DATAPOOL.BPL|IndyCore150.bpl|IndyProtocols150.bpl|IndySystem150.bpl|INPOUT32.DLL|POSVCLGP_150.BPL|WPOCMD.DLL|
        ///對外_POS33=DataSet.bin|DataSet.exe|DataSet.ini|DSCPOSDevice.exe|POSInstall.exe|POSMain.exe|ALTERDB.EXE|CHECKCON [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string tp06_LoadInfo {
            get {
                return ResourceManager.GetString("tp06_LoadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##1.0.0.9
        ///**2012/07/13
        ///1.修改目前版本資訊的標準版顏色為深藍色
        ///2.修改版本為空白時寫入REG錯誤的BUG，增加寫入前判斷版本不可空白
        ///
        ///##1.0.0.10
        ///**2012/07/25
        ///新增判別 32/64 位元PC 機碼路徑
        ///
        ///##1.0.0.11
        ///**2012/07/26
        ///新增ProgPath程式路徑，可自由變更路徑及設定各代號使用路徑
        ///
        ///##1.0.0.12
        ///**2012/09/14
        ///預設版本及路徑的DEF值
        ///
        ///##1.0.0.13
        ///**2012/10/12
        ///增加MENUBAR，增加資訊-&gt;版本說明
        ///
        ///##1.0.0.14
        ///**2012/10/12
        ///1.設定檔INI位置變更為:我的文件\VerTrans\VerTrans.ini，
        ///  若程式在該路徑找不到VerTrans.ini，則會詢問是否新增
        ///2.修正個案代號為空值時，資料帶入的錯誤
        ///3.增加:檔案-&gt;存檔、讀取，現在必須按下存檔才會儲存VerTrans.ini
        ///4.增加:檔案-&gt;設定，可用來設定常用的路徑
        ///
        ///##1.0.0.15
        ///**2012/10/15
        ///修正路 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string VerInfo {
            get {
                return ResourceManager.GetString("VerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No = ALL|21|31|32|33|34|GP1|GP2|GP3 的當地語系化字串。
        /// </summary>
        public static string VerNo {
            get {
                return ResourceManager.GetString("VerNo", resourceCulture);
            }
        }
        
        public static byte[] YaHei_Consolas_1_12 {
            get {
                object obj = ResourceManager.GetObject("YaHei_Consolas_1_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
